version: 2

before:
  hooks:
    - make all

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
      exclude:
      - '^.github:'
      - '^test:'

builds:
  - skip: true

release:
  # prerelease: true
  name_template: "Release v{{.Version}}"